source ~/.vim/options.vim
source ~/.vim/keybinds.vim
source ~/.vim/plugins.vim
source ~/.vim/colors.vim
source ~/.vim/fzf.vim
source ~/.vim/vimtex.vim
source ~/.vim/lightline.vim
source ~/.vim/vim-OSCYank.vim
" source ~/.vim/lsp.vim
source ~/.vim/ftplugin/cpp-build.vim
" source ~/.vim/ftplugin/tex-build.vim

