#!/bin/bash

SCRIPT_DIR="$HOME/.config/fuzzel/scripts"
SELF=$(basename "$0")

choice=$(find "$SCRIPT_DIR" -maxdepth 1 -type f ! -name "$SELF" -exec file {} + | grep "shell script" | cut -d: -f1 | xargs -n1 basename | fuzzel --dmenu --placeholder="Explore your scripts..." --prompt="Fuzzel-Scripts : ")

if [ -n "$choice" ]; then
  bash "$SCRIPT_DIR/$choice"
fi
